version: '3'
services:
  mongodb:
    image: 'mongo:5.0.3'
    container_name: "mj-mongodb"
    ports:
      - '27017:27017'
    networks:
      - backend
  app:
    container_name: "mj-profile"
    depends_on:
      - 'mongodb'
    build:
      context: .
      dockerfile: profile/Dockerfile
    ports:
      - '8080:80'
    expose:
      - '8080:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge