version: '3'
services:
  iwu-mongodb:
    image: 'mongo:5.0.3'
    container_name: "iwu-mongodb"
    networks:
      - backend
  iwu-app:
    image: 'zgys/iwithu:0.1'
    container_name: "iwu-app"
    depends_on:
      - 'iwu-mongodb'
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge