server:
  port: 8100
  http2:
    enabled: true

spring:
  profiles:
    active: dev
  application:
    name: iwithu
  data:
    mongodb:
      database: ${spring.application.name}
      uuid-representation: standard
      host: localhost

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
